version: '3.9'
volumes:
  mongo_db:

services:
#  MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
#  Next service
  next:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/dockerApps
    environment:
      MONGODB_URI: mongodb://mongo_db:27017
      NEXTAUTH_URL: http://localhost:3000/
      NEXTAUTH_SECRET: Le2OxVjEkgx6Yq9B610a7BMH0DtD6jDT06kKsdUWj9I=
    depends_on:
      - mongo_db
