POST http://localhost:3000/api/user/wallet/657f07bf17046c59d26893d3/addTransaction
Content-Type: application/json

{
  "transaction": {
    "date":"2023-12-17",
    "fee": 0.05,
    "from":"bitcoin",
    "price":0.5,
    "quantity":19104.5,
    "to":"eur",
    "type":"sell"
  }
}