POST http://localhost:3000/api/user/wallet/652aa327a4ef30097db1655e/addTransaction
Content-Type: application/json

{
  "transaction": {
    "date":"2023-12-03",
    "fee": 0.00000115,
    "from":"bitcoin",
    "price":0.5,
    "quantity":0.02689267,
    "to":"ethereum",
    "type":"sell"
  }
}